<|./ensorcel
LHS = ${SLHS:%.ℓhs=%.lhs}
ELF = ${SLHS:%.ℓhs=%}

%.lhs: %.ℓhs
	sed -f toascii.sed $stem.ℓhs > $stem.lhs

#%: %.lhs
#	ghc -o $stem $stem.lhs 2>&1 | sed 's,\.lhs,.ℓhs,'

lines: lines.lhs
	ghc -o $target $prereq 2>&1

words: words.lhs
	ghc -o $target $prereq 2>&1

chars: chars.lhs
	ghc -o $target $prereq 2>&1

calc_main: calc_main.lhs calc.lhs constant.lhs UnicodeOperators.lhs
	ghc -fhpc -o $target $prereq --make -fforce-recomp -XRankNTypes

list_main: list_main.lhs list.lhs
	ghc -fhpc -o $target $prereq --make -fforce-recomp

calc_test: calc_test.lhs calc.lhs constant.lhs UnicodeOperators.lhs
	ghc -fhpc -o $target $prereq --make -fforce-recomp -XRankNTypes

list_test: list_test.lhs list.lhs
	ghc -fhpc -o $target $prereq --make -fforce-recomp

%_test: %.lhs

%.run:V: %
	rm -f $stem.tix
	./$stem

%.hpc: %
	hpc markup $stem --exclude=QC

clean:QV:
	rm -f $LHS *.hi *.o *.tix
	rm -f -r .hpc

distclean:QV: clean
	rm -f $ELF
